getwd()

setwd("~/career_da-pffs/udacity-eda/eda-course-materials/lesson4")

Diamonds

As a reminder, you can use these commands to load the diamonds data set.

library(ggplot2) 
#must load the ggplot package first
data(diamonds)
#loads the diamonds data set since it comes with the ggplot package

You need to run these command each time you launch RStudio to access the diamonds data set. RStudio
won't remember which packages and data sets you loaded unless you 
change your preferences or save your workspace.

You should notice that the diamonds data set will be listed as a
'Promise' in the workspace. This is a special object in R, and you need 
to run a command on the data to fully load the data set. Try running a 
summary:

summary(diamonds)

str(diamonds)

qplot(x = price, data = diamonds)

summary(diamonds$price)

How many diamonds cost less than $500?
nrow(subset(diamonds, price < 500))

How many diamonds cost less than $250?
nrow(subset(diamonds, price < 250))

How many diamonds cost $15000 or more?
nrow(subset(diamonds, price >= 15000))

# Scales and Multiple Histograms

qplot(x = price, data = diamonds, binwidth = 30) +
  scale_x_continuous(limits = c(0, 10000), breaks = seq(0, 10000, 1000)) +
  facet_wrap(~cut)
ggsave('priceHistogram.png')

ggplot(data=diamonds) + geom_histogram(binwidth=30, aes(x=diamonds$price)) + 
  ggtitle("Diamond Price Distribution by Cut") +
  xlab("Diamond Price U$") + 
  ylab("Frequency") + 
    facet_wrap(~cut)

Which cut has the highest priced diamond?
premium

Which cut has the lowest priced diamond?
Premium and ideal

Which cut has the lowest median price?
ideal

by(diamonds$price, diamonds$cut, summary)

qplot(x = price, data = diamonds) + facet_wrap(~cut)

The 'Fair' and 'Good' diamonds appear to have 
# different distributions compared to the better
# cut diamonds. They seem somewhat uniform
# on the left with long tails on the right.

# Let's look in to this more.

# Look up the documentation for facet_wrap in R Studio.
# Then, scroll back up and add a parameter to facet_wrap so that
# the y-axis in the histograms is not fixed. You want the y-axis to
# be different for each histogram.

qplot(x = price, data = diamonds) + facet_wrap(~cut, scales="free_y")

#Price per Carat by Cut

Create a histogram of price per carat
# and facet it by cut. You can make adjustments
# to the code from the previous exercise to get
# started.

qplot(x = price/carat, data = diamonds) + facet_wrap(~cut, scales="free_y")

# Adjust the bin width and transform the scale of the x-axis using log10.
qplot(x = price/carat, data = diamonds, binwidth = 50) + facet_wrap(~cut, scales="free_y")

qplot(x = price/carat, data = diamonds, binwidth = 0.05) + 
  facet_wrap(~cut, scales="free_y") +
  scale_x_log10()
ggsave('priceHistogrampricecut.png')


ggplot(diamonds) + geom_histogram(aes(x=price/carat), binwidth = 0.05,
                                  color = "black", fill = "lightblue") +
  ggtitle("Histogram of Price per Carat, facet by Cut.") + 
  scale_x_log10() +
  facet_wrap(. ~ cut, scale='free_y')
  

# Submit your final code when you are ready.
Did you find normal-ish distributions and a slightly bimodal
distribution for Very Good cuts? 
  
Exercise 10: Investigate the price of diamonds 
# using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

qplot(x = cut, y = price, data = diamonds) + 
  geom_boxplot() +
scale_y_continuous(lim = c(0,5000), breaks = seq(0, 6000, 500)) 
ggsave('boxplotpricecut.png')

#fair costs more than good > very good > premium > ideal

qplot(x = clarity, y = price, data = diamonds) + 
  geom_boxplot() +
  scale_y_continuous(lim = c(0,5000), breaks = seq(0, 6000, 500)) 
ggsave('boxplotpriceclarity.png')
#The less clear it is the more it costs

qplot(x = color, y = price, data = diamonds) + 
  geom_boxplot() +
  scale_y_continuous(lim = c(0,5000), breaks = seq(0, 6000, 500)) 
ggsave('boxplotpricecolor.png')

# price increases from  D to J with some exceptions like G

qplot(x = color, y = price, data = diamonds, geom = "boxplot") + 
  coord_cartesian(ylim = c(0,8000))

str(diamonds)

#Excercise 11: Interquartile range - IQR

a) What is the price range for the middle 50% of diamonds with color D?
  by(diamonds$price, diamonds$color, summary)
b) What is the price range for the middle 50% of diamonds with color J?
  by(diamonds$price, diamonds$color, summary)
  
c) What is the IQR for diamonds with the best color?
  by(diamonds$price, diamonds$color, IQR)
d) What is the IQR for diamonds with the worst color?
  by(diamonds$price, diamonds$color, IQR)

Note: For boxplots, we use the "y" parameter for the continuous data 
and the "x" parameter for the categorical data.

# Ex. 12 Investigate the price per carat of diamonds across
# the different colors of diamonds using boxplots.

qplot(x = color, y = price/carat, data = diamonds, fill=color) + 
  geom_boxplot() +
  scale_y_continuous(lim = c(0,6000), breaks = seq(0, 6000, 500)) 
ggsave('boxplotpricepercarat.png')

qplot(x = color, y = price/carat, data = diamonds, geom = "boxplot") + 
  coord_cartesian(ylim = c(0,8000) 
                  
# The price increases from D dark to J bright
                  
# Carat frequency polygon

Investigate the weight of the diamonds (carat) using a frequency polygon. Use different bin widths to see how the frequency polygon changes.
Use different bin widths to see how the frequency polygon
changes.What carat size has a count greater than 2000?

??freqpoly

ggplot(diamonds) + 
  geom_freqpoly(aes(x = carat), binwidth = 0.1) +
  scale_x_continuous(breaks = seq(0,5,0.2))
 ggsave('wgtfreqpoly.png')

or

qplot(data=diamonds, x=carat, xlab='Carat', ylab='Frequency', 
      binwidth=0.1, geom='freqpoly') + 
  scale_x_continuous(breaks=seq(0,5,0.2)) + 
  scale_y_continuous(breaks=seq(0,12000,2000))


Data Wrangling with R

Data munging or data wrangling can take up much of a data scientist's or 
data analyst's time. There are two R packages that make these tasks easier in R:
  tidyr and dplyr.

tidyr -a package that reshapes the layout of your data

dplyr - a package that helps you transform tidy, tabular data

Review Data Wrangling in R to get a sense of how these packages allow you to manipulate
data. You can use these packages to help you in the next programming task and in your
future investigations.

There are some useful cheat sheets on RStudio's webpage. The Data Import and Data 
Transformation cheat sheets available at that site will be especially good references 
for working with tidyr and dplyr, respectively.


# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to download a data set of your choice
# and create 2-5 plots that make use of the techniques from Lesson 3.



# You might use a simple histogram, a boxplot split over a categorical variable,
# or a frequency polygon. The choice is yours!

# You can find a link to the Gapminder website in the Instructor Notes.
  
  

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

There are other data sets that come with R. You can load these data sets
by typing the command data(DATA_SET_NAME).

You can learn more about the diamonds data set by typing ?diamonds.

Read the help file to determine the best color for the diamonds
data set. When you run diamonds$color, you will notice that the 
levels of color are set as D < E < F < ...

This does not indicate that D is the worst color but rather an ordering
to the colors.





